version: 2
jobs:
 build:
  docker:
   # specify the version you desire here
   - image: circleci/node:latest
  working_directory: ~/repo
  steps:
   - checkout
   - run: npm install
   - run: npm test
   - setup_remote_docker
   - run:
      name: Push Docker Image
      command: |
       docker login -u $DOCKER_USER -p $DOCKER_PASS
       docker build -t k8stest .
       docker tag k8stest "heinrich10/k8stest:1.1.${CIRCLE_BUILD_NUM}"
       docker push "heinrich10/k8stest:1.1.${CIRCLE_BUILD_NUM}"
   - run:
      name: Install kubectl
      command: |
       curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
       chmod +x ./kubectl
       sudo mv ./kubectl /usr/local/bin/kubectl
   - run:
      name: Update Kubernetes
      command: |
       mkdir ~/.kube
       cp ./config/kube ~/.kube/config
       kubectl set image deployment/k8stest-deployment k8stest=heinrich10/k8stest:1.1.${CIRCLE_BUILD_NUM}
